import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight } from "lucide-react";

const ICON = "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/e9/dc/45/e9dc45ac-cc5b-9a88-4127-16f4893ee626/AppIcon-0-0-1x_U007emarketing-0-11-0-85-220.png/512x512bb.jpg";

export default function PrivacyPolicy() {
  return <main>
    <nav className="nav shell privacy-nav"><Link href="/" className="brand"><Image src={ICON} alt="Prestuds" width={42} height={42} /><span>prestuds</span></Link><Link className="nav-cta" href="/">Home <ArrowUpRight size={16} /></Link></nav>
    <article className="privacy-main">
      <Link className="back" href="/"><ArrowLeft size={15} /> Back to Prestuds</Link>
      <header className="privacy-hero"><span className="kicker">Your data, explained clearly</span><h1>Privacy Policy</h1><p>This policy explains what information Prestuds may collect, why we use it, and the choices you have. We believe privacy information should be as organized and understandable as your semester.</p><span className="updated">Last updated: 16 August 2026</span></header>
      <div className="privacy-content">
        <section><h2>1. About this policy</h2><p>This Privacy Policy applies to the Prestuds student planner application and related services operated by Velton Tech Inc. (“Prestuds,” “we,” “us,” or “our”). By using Prestuds, you acknowledge the practices described here.</p></section>
        <section><h2>2. Information we collect</h2><p>We collect only the information needed to provide, improve, and protect Prestuds. The information available to us depends on the features you choose to use.</p>
          <div className="data-table"><div className="data-row header"><span>Data</span><span>Examples</span><span>Why we use it</span></div><div className="data-row"><span>Contact information</span><span>Name and email address</span><span>Account access, support, and app functionality</span></div><div className="data-row"><span>Usage data</span><span>Product interactions and feature activity</span><span>App functionality, personalisation, and analytics</span></div><div className="data-row"><span>User content</span><span>Photos or videos you choose to attach</span><span>To provide the features you request</span></div><div className="data-row"><span>Diagnostics</span><span>Crash data and technical logs</span><span>Reliability, troubleshooting, and analytics</span></div></div>
          <h3>Academic and user-created content</h3><p>You may add class schedules, subjects, assignments, exams, notes, documents, and reminder preferences. We process this content to provide the planner features you request. Please avoid uploading sensitive personal information that is not needed for your studies.</p>
          <h3>AI-assisted features</h3><p>If you use an AI-assisted feature, the text you submit may be processed to generate the requested result, such as helping structure a semester schedule. Do not include confidential or highly sensitive information in AI prompts.</p></section>
        <section><h2>3. How we use information</h2><ul><li>Provide and maintain your account, schedules, reminders, notes, and attachments.</li><li>Personalize how Prestuds works for you.</li><li>Understand feature use and improve the product.</li><li>Detect, investigate, and fix crashes or technical problems.</li><li>Respond to support requests and communicate important service information.</li><li>Protect the security and integrity of Prestuds and comply with legal obligations.</li></ul></section>
        <section><h2>4. How information is shared</h2><p>We do not sell your personal information. We may share limited information with service providers that help us operate Prestuds, such as hosting, analytics, crash reporting, authentication, file storage, payment, and AI-processing providers. They may process information only to perform services for us and subject to appropriate safeguards.</p><p>We may also disclose information when required by law, to protect rights and safety, or as part of a merger, acquisition, financing, or sale of assets. If you choose to share a schedule by QR code, the information included in that share is made available to the people you choose.</p></section>
        <section><h2>5. Data retention and security</h2><p>We retain information for as long as reasonably necessary to provide Prestuds, fulfill the purposes described in this policy, resolve disputes, and meet legal obligations. Retention periods vary by data type. We use reasonable administrative, technical, and organizational safeguards, but no method of electronic storage or transmission is completely secure.</p></section>
        <section><h2>6. Your choices and rights</h2><p>Depending on where you live, you may have rights to access, correct, delete, or receive a copy of your personal information, or to object to or restrict certain processing. You can also limit device permissions such as photo access or notifications through your device settings. To make a privacy request, contact us using the details below.</p></section>
        <section><h2>7. Children’s privacy</h2><p>Prestuds is a general student-planning tool and is not directed to children under 13, or the minimum age required in their country to consent to data processing. We do not knowingly collect personal information from children below that age without appropriate authorization. If you believe a child has provided personal information improperly, please contact us.</p></section>
        <section><h2>8. International processing</h2><p>Our service providers may process information in countries other than the one where you live. Where required, we use appropriate safeguards for international transfers of personal information.</p></section>
        <section><h2>9. Changes to this policy</h2><p>We may update this policy as Prestuds evolves or legal requirements change. We will post the updated version here and revise the “Last updated” date. If a change is significant, we may provide an additional notice in the app.</p></section>
        <section><h2>10. Contact us</h2><p>If you have questions or a privacy request, contact the Prestuds team:</p><div className="contact-box"><p><b>Velton Tech Inc.</b></p><p>Developer: Muhamad Nur Asyraaf</p><p>Email: <a href="mailto:support@prestuds.app"><u>support@prestuds.app</u></a></p></div></section>
      </div>
    </article>
    <footer className="footer shell"><Link href="/" className="brand"><Image src={ICON} alt="" width={34} height={34} /><span>prestuds</span></Link><p>Plan less. Learn more.</p><div><Link href="/privacy">Privacy Policy</Link><a href="https://apps.apple.com/my/app/prestuds-student-planner/id6752947237">App Store</a></div><small>© 2026 Velton Tech Inc.</small></footer>
  </main>;
}
